### ISSUE TITLE
【报错求助】使用Safety Checker报错

### ISSUE THREAD

**Issue by Xian0Grem** [iyume/nonebot-plugin-nsfw#14]
报错内容

11-11 01:17:20 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_nsfw, lineno=57) failed.
  + Exception Group Traceback (most recent call last):
  |   File "F:\NoneBot\nonebot_liyu\debug\bot.py", line 46, in <module>
  |     nonebot.run()
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
  |     get_driver().run(*args, **kwargs)
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
  |     uvicorn.run(
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
  |     server.run()
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
  |     return asyncio.run(self.serve(sockets=sockets))
  |   File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
  |     return runner.run(main)
  |   File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |   File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
  |     self.run_forever()
  |   File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
  |     super().run_forever()
  |   File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
  |     self._run_once()
  |   File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
  |     handle._run()
  |   File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
  |     self._context.run(self._callback, *self._args)
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
  |     return await coro
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
  |     await _run_matcher(
  | > File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
  |     await matcher.run(bot, event, state, stack, dependency_cache)
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 891, in run
  |     with catch(
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\exceptiongroup\_catch.py", line 39, in __exit__
  |     raise unhandled from exc.__cause__
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
  |     await self.simple_run(bot, event, state, stack, dependency_cache)
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 822, in simple_run
  |     with catch({StopPropagation: _handle_stop_propagation}):
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\exceptiongroup\_catch.py", line 39, in __exit__
  |     raise unhandled from exc.__cause__
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 836, in simple_run
  |     with catch({SkippedException: _handle_skipped}):
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\exceptiongroup\_catch.py", line 39, in __exit__
  |     raise unhandled from exc.__cause__
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
  |     await handler(
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 104, in __call__
  |     with catch({SkippedException: _handle_skipped}):
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\exceptiongroup\_catch.py", line 39, in __exit__
  |     raise unhandled from exc.__cause__
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 109, in __call__
  |     values = await self.solve(**kwargs)
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 219, in solve
  |     async with anyio.create_task_group() as tg:
  |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    |     return await coro
    |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 216, in _solve_field
    |     value = await self._solve_field(field, params)
    |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 199, in _solve_field
    |     value = await param._solve(**params)
    |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot\internal\params.py", line 309, in _solve
    |     result = await target
    |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot_plugin_nsfw\deps.py", line 62, in detect_nsfw
    |     await _process_images(event, images, have_nsfw)
    |   File "F:\NoneBot\nonebot_liyu\debug\.venv\Lib\site-packages\nonebot_plugin_nsfw\deps.py", line 76, in _process_images
    |     nsfw_images = [i[0] for i in zip(images, have_nsfw) if i[1]]
    | TypeError: 'bool' object is not iterable
    +------------------------------------

**Comment by iyume** [comment]
safety-checker 那边发了新版，但是这边的代码忘了跟进

**Comment by iyume** [comment]
0.12 已发版
