### ISSUE TITLE
建议检测前先判断自己是不是群管理员

### ISSUE THREAD

**Issue by mmmjie** [iyume/nonebot-plugin-nsfw#4]
默认打开的情况下，bot在某些群不是群管理员，然后检测到又撤回不了，就在那报错，浪费服务器资源。。。

**Comment by iyume** [comment]
已添加支持，见  v0.10，有问题再及时反馈。

实现流程为在群调用一次身份 api 并检测资格和缓存，检测管理员变动并更改缓存。
