### ISSUE TITLE
有点奇怪，我试了一会好像bool不论返回什么，rule都会算全满足触发

### ISSUE THREAD

**Issue by mmmjie** [iyume/nonebot-plugin-nsfw#5]
即便不是群管理，或者我修改bool固定返回false，只要是色图一样会触发这个撤回行为

**Comment by mmmjie** [comment]
对于非色图不撤回，色图才撤回的判断没问题

但控制不了这插件，发图必测

**Comment by mmmjie** [comment]
我换一个环境又正常了，奇怪，也没报错啊。。。

**Comment by iyume** [comment]
可能是插件版本不一致，bot 自身的管理员检测是 v0.10 引入的。

**Comment by mmmjie** [comment]
> 可能是插件版本不一致，bot 自身的管理员检测是 v0.10 引入的。

发现问题了。。。

之前我装模型的时候，把这插件本体也用作依赖装进虚拟环境了

我使用真寻是使用“手动放进文件夹然后加载”的形式来使用

插件使用from nonebot_plugin_nsfw.loader import run_loader_thread 的形式来导入函数
这就导致了，不管我手动怎么修改加载的插件，但最后都引入了环境里 旧版的插件函数



感觉一般用from .loader import run_loader_thread  的形式来导入本插件其他函数的比较多一些，
我也很少遇到这种的，所以一下找不到问题

**Comment by mmmjie** [comment]
我自己问题，不好意思.

**Comment by mmmjie** [comment]
有时候发一个色图会警告2次，感觉可能是重复执行了引入的函数，外加插件本身的函数，不过我对代码这块有点苦手，不是很确定

**Comment by iyume** [comment]
> 有时候发一个色图会警告2次，感觉可能是重复执行了引入的函数，外加插件本身的函数，不过我对代码这块有点苦手，不是很确定

有可能是协议端消息堆积引起的，你需要看看协议端的 log 是不是给 nb 推送了两次。
